[General]
loglevel = notify
dns-server = system, 1.1.1.1, 8.8.8.8

[Proxy]

[Proxy Group]
PROXY = select, DIRECT

[Rule]
# surge-profile-relay:managed
# 此段由 Surge Shallow 自动生成，请在应用中修改规则源。
DOMAIN-SUFFIX,example.com,PROXY
IP-CIDR,192.0.2.0/24,DIRECT,no-resolve
FINAL,DIRECT
